// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "memoANDtimekensan",
    platforms: [
        .macOS(.v12)
    ],
    products: [
        .executable(name: "memoANDtimekensan", targets: ["memoANDtimekensan"]),
    ],
    targets: [
        .executableTarget(
            name: "memoANDtimekensan",
            dependencies: []
        ),
        .testTarget(
            name: "memoANDtimekensanTests",
            dependencies: ["memoANDtimekensan"]
        ),
    ]
)
